language: ruby
rvm:
  - 2.3

before_install:
  - eval "$(ssh-agent -s)"
  - openssl aes-256-cbc -K $encrypted_7d60601be663_key -iv $encrypted_7d60601be663_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - ssh-add deploy_key

script:
  - bundle exec rake deploy
