language: ruby
rvm:
- 2.3

cache:
  bundler: true
  directories:
  - build
  - caches

before_install:
- sudo apt-get install -y libexif-dev
- openssl aes-256-cbc -K $encrypted_6e681cddc229_key -iv $encrypted_6e681cddc229_iv -in secrets.tar.gz.enc -out secrets.tar.gz -d
- tar xvzf secrets.tar.gz
- chmod 600 secrets/*
- git remote set-url origin $(git remote get-url origin | sed -e 's/https:\/\/github.com\//git@github.com:/')
- eval "$(ssh-agent -s)"
- ssh-add secrets/deploy_key
- 'echo "commit_url: \"https://github.com/${TRAVIS_REPO_SLUG}/commit/${TRAVIS_COMMIT}\""
  >> _config_prod.yml'
- 'echo "commit_hash: \"${TRAVIS_COMMIT:0:7}\"" >> _config_prod.yml'

script:
- bundle exec rake prepare deploy
