language: ruby
rvm:
  - 2.3

before_install:
  - git remote set-url origin $(git remote get-url origin | sed -e 's/https:\/\/github.com\//git@github.com:/')
  - eval "$(ssh-agent -s)"
  - openssl aes-256-cbc -K $encrypted_7d60601be663_key -iv $encrypted_7d60601be663_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - ssh-add deploy_key
  - 'echo "commit_url: \"https://github.com/${TRAVIS_REPO_SLUG}/commit/${TRAVIS_COMMIT}\"" >> _config_prod.yml'
  - 'echo "commit_hash: \"${TRAVIS_COMMIT:0:7}\"" >> _config_prod.yml'

script:
  - bundle exec rake prepare deploy
